name: Build Test2

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *' # run every day at 16:20 UTC / 8:20 PST

concurrency:
  group: ${{ github.workflow }}

jobs:
  build1:
  

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          7.0.x
    - name: Restore dependencies
      run: dotnet restore src/YouRatta.Common/
    - name: Build Test
      run: dotnet build src/YouRatta.Common/ --no-restore
    - name: Restore dependencies2
      run: dotnet restore src/YouRatta.ConflictMonitor/
    - name: Build Test2
      run: dotnet build src/YouRatta.ConflictMonitor/ --no-restore
    - name: Restore dependencies3
      run: dotnet restore src/YouRatta.InitialSetup/
    - name: Build Test3
      run: dotnet build src/YouRatta.InitialSetup/ --no-restore
    - name: Test (I:Debug T:Debug R:false)
      run: dotnet run --verbosity normal --project src/YouRatta.ConflictMonitor/YouRatta.ConflictMonitor.csproj --no-build src/YouRatta.ConflictMonitor/Debug/net7.0/YouRatta.ConflictMonitor.dll &
      env:
        ACTION_TOKEN : ${{ secrets.GITHUB_TOKEN }}
    - name: Test2 (I:Debug T:Debug R:false)
      run: dotnet run --verbosity normal --project src/YouRatta.InitialSetup/YouRatta.InitialSetup.csproj --no-build src/YouRatta.InitialSetup/Debug/net7.0/YouRatta.InitialSetup.dll
    - name: env
      run: env
