name: Build Test2

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *' # run every day at 16:20 UTC / 8:20 PST

concurrency:
  group: ${{ github.workflow }}

jobs:
  build1:
  

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          7.0.x
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
    - name: Restore dependencies
      run: dotnet restore src/YouRatta.Common/
    - name: Build Test
      run: dotnet build src/YouRatta.Common/ --no-restore
    - name: Restore dependencies2
      run: dotnet restore src/YouRatta.ConflictMonitor/
    - name: Build Test2
      run: dotnet build src/YouRatta.ConflictMonitor/ --no-restore
    - name: Restore dependencies3
      run: dotnet restore src/tester/
    - name: Build Test3
      run: dotnet build src/tester/ --no-restore
    - name: Test (I:Debug T:Debug R:false)
      run: dotnet run --verbosity normal --project src/YouRatta.ConflictMonitor/YouRatta.ConflictMonitor.csproj --no-build src/YouRatta.ConflictMonitor/Debug/net7.0/YouRatta.ConflictMonitor.dll & 
    - name: Test2 (I:Debug T:Debug R:false)
      run: dotnet run --verbosity normal --project src/tester/tester.csproj --no-build src/tester/Debug/net7.0/tester.dll
    - name: ls
      run: ls
